import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ShieldCheck, UsersRound } from "lucide-react";
import { Logo } from "@/components/Logo";

const sections = [
  ["1. Acceptance and member registration", "You must read and accept these Member Terms & Conditions before creating a METHO member account. Registration is subject to verification and approval under METHO's operational rules. It does not guarantee income, incentives, rank, earnings, business results, or any particular benefit."],
  ["2. METHO's platform role", "METHO provides a technology platform and administrative framework for member accounts, eligible purchases, referral records, wallet activity, Smart Cycle records, and related services. METHO may operate its own products and services or connect members with independent partners, but does not guarantee any independent partner's goods, services, promises, conduct, or availability except where required by applicable law."],
  ["3. Eligibility, accurate information and account security", "Members must provide genuine, accurate, current, and lawfully obtained identity, contact, PAN, bank, payment, and registration information. Members must protect login credentials, not share access, and promptly report unauthorised account activity. A member is responsible for activity performed through that member's account unless caused by METHO's own fault."],
  ["4. Smart Cycle, rewards and referrals", "Rewards, Smart Cycle benefits, wallet credits, commissions, rankings, and referral-related benefits are calculated only under the official rules, eligibility conditions, approved transactions, and applicable limits in force at the relevant time. They are not an investment return, fixed income, employment payment, or guarantee of future earnings. METHO may correct errors, reverse ineligible credits, and update programme rules with notice through official channels where appropriate."],
  ["5. Indian law and member conduct", "Members must comply with all applicable laws of India, tax and consumer-protection requirements, anti-fraud rules, and lawful authority directions. Members must not create fake orders, misrepresent products, benefits, or earnings, forge documents, misuse referral links, manipulate transactions, harass others, or use METHO services for unlawful activity."],
  ["6. Purchases, third-party partners and disputes", "Members should review listing details, supplier terms, invoices, and applicable cancellation or return conditions before a purchase. Independent partners and service providers remain responsible for the goods and services they supply. METHO may assist with escalation where available but does not assume an independent provider's operational responsibility except where liability cannot lawfully be excluded."],
  ["7. Privacy, suspension and governing law", "METHO uses member information to operate accounts, process eligible transactions, provide support, prevent fraud, and meet legal obligations. METHO may restrict, suspend, or terminate an account for inaccurate information, fraud, policy breach, safety concerns, or a lawful authority request. These terms are governed by applicable laws of India, subject to mandatory consumer-protection jurisdiction."],
];

export default function MemberTermsPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-700">
    <header className="border-b border-emerald-900/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-4"><Logo showTagline /><Link to="/register" className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-900 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> Member Registration</Link></div></header>
    <main className="mx-auto max-w-4xl px-6 py-12"><article className="rounded-xl border border-emerald-900/10 bg-white p-6 shadow-sm md:p-10"><div className="flex items-start gap-3"><div className="rounded-lg bg-emerald-100 p-2 text-emerald-800"><UsersRound className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-800">METHO Membership</p><h1 className="mt-1 font-display text-3xl font-black tracking-tight text-emerald-950 md:text-4xl">Member Terms &amp; Conditions</h1><p className="mt-2 text-sm text-slate-500">Version 2026-08-22 · Applies only to METHO member registration and membership activity in India.</p></div></div><p className="mt-7 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" />Member rewards and Smart Cycle benefits are eligibility-based programme benefits, not assured earnings or an investment return.</p><div className="mt-8 space-y-7 text-sm leading-7">{sections.map(([title, body]) => <section key={title}><h2 className="font-display text-xl font-bold text-emerald-950">{title}</h2><p className="mt-2">{body}</p></section>)}</div></article></main>
  </div>;
}