import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, CarTaxiFront, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";

const sections = [
  ["1. Acceptance and booking request", "You must read and accept these Customer Terms & Conditions before requesting or paying for a METHO Move or METHO Delivery booking. A route request, estimated fare, payment acknowledgement, or booking reference is not a guarantee that a rider, vehicle, pickup time, or delivery will be available."],
  ["2. METHO Move's role", "METHO Move acts only as an intermediary technology platform and administrative facilitator that may connect customers with independent riders. METHO Move does not itself conduct, operate, control, or provide a ride, delivery, vehicle, driver, transport operation, or on-road service."],
  ["3. Independent rider service", "A rider independently accepts and conducts a ride or delivery. The rider is responsible for the vehicle, driving, route operation, permits, insurance, legal compliance, and service delivered. METHO Move may assist with booking coordination and issue escalation but does not assume an independent rider's operational responsibility except where liability cannot lawfully be excluded."],
  ["4. Customer responsibilities and Indian law", "Customers must provide accurate pickup, destination, contact, parcel, and passenger information; comply with all applicable laws of India and lawful authority directions; behave safely and respectfully; and not request transport of prohibited, unlawful, dangerous, or undeclared goods. Customers are responsible for ensuring that any person travelling with them is authorised and able to travel lawfully."],
  ["5. Fare, route and payment", "An estimated amount is based on the requested route and configured service rate and may require confirmation if the route, distance, waiting time, service conditions, or booking details change. Payment is processed through the selected payment method. Do not share a UPI PIN, card PIN, CVV, or OTP with a rider or anyone claiming to represent METHO Move."],
  ["6. Safety, cancellation and service issues", "Customers must use reasonable safety precautions, follow lawful safety instructions, and report urgent safety matters to the relevant emergency authority. Cancellation, changes, refunds, waiting charges, or fare adjustments depend on the booking status, rider availability, service already provided, and applicable law. Report an issue promptly with the booking reference and supporting details so it can be escalated."],
  ["7. Privacy and governing law", "Customer contact and booking details are used to arrange the requested service, process payment, provide support, prevent fraud, and meet legal obligations. Information may be shared with the assigned rider only as needed for the booking. These terms are governed by applicable laws of India, subject to mandatory consumer-protection jurisdiction."],
];

export default function MethoMoveCustomerTermsPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-700">
    <header className="border-b border-emerald-900/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-4"><Logo showTagline /><Link to="/metho-move" className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-900 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> METHO Move Booking</Link></div></header>
    <main className="mx-auto max-w-4xl px-6 py-12"><article className="rounded-xl border border-emerald-900/10 bg-white p-6 shadow-sm md:p-10"><div className="flex items-start gap-3"><div className="rounded-lg bg-emerald-100 p-2 text-emerald-800"><CarTaxiFront className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-800">METHO Move / METHO Delivery</p><h1 className="mt-1 font-display text-3xl font-black tracking-tight text-emerald-950 md:text-4xl">Customer Terms &amp; Conditions</h1><p className="mt-2 text-sm text-slate-500">Version 2026-08-22 · Applies only to customer ride and delivery booking requests in India.</p></div></div><p className="mt-7 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" />METHO Move is an intermediary platform. Independent riders conduct services; customers must comply with Indian law and these booking terms.</p><div className="mt-8 space-y-7 text-sm leading-7">{sections.map(([title, body]) => <section key={title}><h2 className="font-display text-xl font-bold text-emerald-950">{title}</h2><p className="mt-2">{body}</p></section>)}</div></article></main>
  </div>;
}