import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Building2, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";

const sections = [
  ["1. Acceptance and partner registration", "You must read and accept these Partner Terms & Conditions before submitting a METHO partner application. Registration, profile creation, directory visibility, or admin approval does not guarantee customers, orders, earnings, settlement, or any business outcome."],
  ["2. METHO's role", "METHO acts only as an intermediary technology platform and administrative facilitator. It may provide listing, ordering, payment coordination, reporting, and support tools, but does not manufacture, own, inspect, certify, guarantee, endorse, control, or assume responsibility for an independent partner's business, staff, products, services, premises, documents, or customer promises except where required by applicable law."],
  ["3. Partner responsibility", "The partner alone is responsible for product and service quality, pricing, warranty, delivery, fulfilment, after-sales support, customer communication, staff conduct, business operations, and every representation made through the partner profile or otherwise. The partner must resolve operational complaints and disputes arising from its own business promptly and lawfully."],
  ["4. Indian law, licences and compliance", "The partner must comply with all applicable laws of India and state or local authority requirements, including tax, consumer-protection, labour, business registration, licence, permit, food safety, health, transport, sector-specific, advertising, data, and safety obligations relevant to its business. The partner must maintain all registrations, licences, certificates, insurance, and approvals required for lawful operation."],
  ["5. Accurate information and documents", "Every product, service, price, description, image, certificate, licence, registration number, tax detail, and supporting document provided to METHO must be genuine, accurate, complete, current, and legally valid. The partner is solely responsible for any incorrect, misleading, expired, forged, unauthorised, or invalid information and its resulting losses, penalties, claims, disputes, liabilities, or legal consequences."],
  ["6. Marketplace conduct and customer safety", "Partners must treat customers fairly, honour lawful commitments, provide clear pricing and conditions, protect customer information, avoid unfair trade practices, and never offer prohibited, counterfeit, unsafe, or unlawful goods or services. A partner must promptly report a material safety, fraud, legal, or customer incident that affects a METHO booking or order."],
  ["7. Payments, fees and disputes", "Applicable charges, commissions, settlements, taxes, refunds, and adjustments are handled under the relevant product, service, order, and programme rules. METHO may hold, reverse, adjust, or delay a settlement where reasonably necessary for fraud prevention, customer protection, correction of an error, legal compliance, or a disputed transaction. Nothing limits rights that cannot lawfully be excluded."],
  ["8. Suspension, termination and governing law", "METHO may suspend, restrict, remove, or terminate a partner profile for inaccurate information, expired documents, safety concerns, fraud, policy breach, customer harm, repeated complaints, or a lawful authority request. These terms are governed by applicable laws of India, subject to mandatory consumer-protection jurisdiction."],
];

export default function PartnerTermsPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-700">
    <header className="border-b border-emerald-900/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-4"><Logo showTagline /><Link to="/partner-register" className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-900 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> Partner Registration</Link></div></header>
    <main className="mx-auto max-w-4xl px-6 py-12"><article className="rounded-xl border border-emerald-900/10 bg-white p-6 shadow-sm md:p-10"><div className="flex items-start gap-3"><div className="rounded-lg bg-emerald-100 p-2 text-emerald-800"><Building2 className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-800">METHO Partner Network</p><h1 className="mt-1 font-display text-3xl font-black tracking-tight text-emerald-950 md:text-4xl">Partner Terms &amp; Conditions</h1><p className="mt-2 text-sm text-slate-500">Version 2026-08-22 · Applies only to METHO partner registration and partner activity in India.</p></div></div><p className="mt-7 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" />METHO is an intermediary technology platform. Each independent partner remains responsible for its own business, legal compliance, customer service, products, and services.</p><div className="mt-8 space-y-7 text-sm leading-7">{sections.map(([title, body]) => <section key={title}><h2 className="font-display text-xl font-bold text-emerald-950">{title}</h2><p className="mt-2">{body}</p></section>)}</div></article></main>
  </div>;
}