import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Bike, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";

const sections = [
  ["1. Acceptance and registration", "You must read and accept these Rider Terms & Conditions before submitting a METHO Move rider registration. Registration, approval, profile activation, or a ride request does not create an employment relationship, guarantee earnings, or guarantee ride allocation."],
  ["2. METHO Move's role", "METHO Move acts only as an intermediary technology platform and administrative facilitator that may connect customers with independent riders. METHO Move does not itself conduct, operate, control, or provide any ride, delivery, vehicle, driver, transport service, or on-road operation."],
  ["3. Rider's independent responsibility", "The rider alone is responsible for accepting or declining a request, operating the vehicle safely, completing the ride or delivery, passenger conduct while in the rider's care, route choices, traffic compliance, service quality, and every consequence arising from the rider's own acts, omissions, vehicle, documents, or conduct."],
  ["4. Indian law, licences and vehicle compliance", "The rider must comply with all applicable laws of India and all state and local authority requirements, including motor vehicle, road traffic, transport, labour, tax, insurance, consumer-protection, safety, permit, and licensing rules. The rider must maintain a valid driving licence, registration, insurance, permits, fitness documents, tax records, and any category-specific authorisation required for the vehicle and service."],
  ["5. Safety and rider conduct", "The rider must operate a roadworthy vehicle, follow traffic rules, use legally required safety equipment, avoid intoxication or unsafe driving, treat customers respectfully, protect passenger and customer information, and never engage in harassment, discrimination, violence, fraud, overcharging, or unlawful activity. The rider must not carry prohibited goods or undertake an unsafe or unlawful trip."],
  ["6. Accuracy of information", "All registration information, identity details, vehicle details, bank and payment information, licences, certificates, and documents supplied by the rider must be genuine, accurate, current, and submitted with authority. The rider must promptly update any expired, suspended, changed, or incorrect information."],
  ["7. Incidents, claims and liability", "For an accident, injury, loss, delay, traffic violation, police matter, customer dispute, insurance claim, vehicle failure, or any other ride-related problem, the rider must take lawful and reasonable safety steps, notify the relevant authority or insurer where required, and promptly report the matter to METHO Move. The rider remains responsible for liabilities, penalties, claims, losses, and legal consequences arising from the rider's conduct or operation, except where responsibility cannot lawfully be excluded."],
  ["8. Suspension, removal and governing law", "METHO Move may suspend, restrict, or remove a rider profile for inaccurate information, expired documents, safety concerns, customer complaints, fraud, breach of these terms, or a lawful authority request. These terms are governed by applicable laws of India, subject to mandatory legal and consumer-protection jurisdiction."],
];

export default function RiderTermsPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-700">
    <header className="border-b border-emerald-900/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-4"><Logo showTagline /><Link to="/rider-register" className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-900 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> Rider Registration</Link></div></header>
    <main className="mx-auto max-w-4xl px-6 py-12"><article className="rounded-xl border border-emerald-900/10 bg-white p-6 shadow-sm md:p-10"><div className="flex items-start gap-3"><div className="rounded-lg bg-emerald-100 p-2 text-emerald-800"><Bike className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-800">METHO Move</p><h1 className="mt-1 font-display text-3xl font-black tracking-tight text-emerald-950 md:text-4xl">Rider Terms &amp; Conditions</h1><p className="mt-2 text-sm text-slate-500">Version 2026-08-22 · Applies only to METHO Move rider registration and ride activity in India.</p></div></div><p className="mt-7 flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" />METHO Move is an intermediary platform. Riders independently conduct rides and remain responsible for lawful, safe vehicle operation and ride-related issues.</p><div className="mt-8 space-y-7 text-sm leading-7">{sections.map(([title, body]) => <section key={title}><h2 className="font-display text-xl font-bold text-emerald-950">{title}</h2><p className="mt-2">{body}</p></section>)}</div></article></main>
  </div>;
}