import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";

const sections = [
  ["1. Scope and booking status", "METHO provides a digital booking and coordination channel for travel services. A selected date, payment acknowledgement, or order reference is not a supplier confirmation unless METHO or the named service supplier confirms the itinerary, availability, and booking reference in writing."],
  ["2. Price, inclusions and exclusions", "The displayed amount applies only to the service described in the listing. Transport, meals, entry tickets, permits, taxes, insurance, baggage, personal expenses, supplier surcharges, and other items are excluded unless expressly stated in the written confirmation. Any change in traveller count, route, dates, room category, or supplier availability may change the payable amount; the customer must approve any revised amount before it is collected."],
  ["3. Traveller information and documents", "The lead traveller is responsible for accurate names, age, contact details, identity documents, permits, visas, medical declarations, and consent for every traveller. Requirements vary by destination and supplier. METHO does not guarantee admission, boarding, entry, or permit approval where documents, health requirements, age limits, or authority directions are not met."],
  ["4. Cancellation, changes and refunds", "Cancellation or change requests must be made through the booking support channel from the registered mobile number. Refund eligibility, timing, and deductions depend on the confirmed supplier terms, non-refundable components, elapsed time before departure, and services already delivered. Statutory or supplier deductions, bank/payment charges, and documented administrative charges may apply where disclosed in the confirmation. No refund is due for no-shows, late arrival, incorrect traveller details, or a traveller's failure to meet required conditions."],
  ["5. Availability, force majeure and safety", "Travel is subject to weather, traffic, operational limitations, government or local authority directions, strikes, public-health measures, supplier disruption, natural events, and other events outside reasonable control. Where possible, METHO will coordinate an alternative, credit, or refund available from the supplier; it cannot promise an outcome beyond the applicable supplier or legal entitlement. Travellers must follow lawful instructions, safety rules, accommodation rules, and reasonable instructions of operators and authorities."],
  ["6. Supplier responsibility and complaints", "Hotels, transporters, guides, activity operators, and other third parties remain responsible for the services they operate. METHO will reasonably assist with booking coordination and complaint escalation, but does not assume responsibility for an independent supplier's acts, omissions, service quality, or unsafe conduct except where liability cannot lawfully be excluded. Report an on-trip issue as soon as possible with the booking reference and supporting details so that corrective action can be attempted."],
  ["7. Privacy, payment and fraud prevention", "Booking details and limited traveller information are used to arrange the requested service, process payment, provide support, prevent fraud, and meet legal or tax obligations. Information may be shared with the relevant supplier only as needed for the booking. Never share UPI PIN, card PIN, CVV, or OTP with METHO staff or suppliers. Payment is processed through the selected method; a chargeback or dispute does not by itself cancel a confirmed service."],
  ["8. Consumer rights, governing process and contact", "Nothing in these terms limits rights that cannot be excluded under applicable Indian law. Before paying, customers should review the listing, supplier confirmation, cancellation terms, invoice, and any destination-specific requirements. For assistance or a grievance, contact METHO from the registered mobile number and retain the order reference, payment reference, and relevant evidence. These terms are governed by applicable laws of India, subject to mandatory consumer-protection jurisdiction."],
];

export default function TravelBookingTermsPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-700">
    <header className="border-b border-sky-900/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-4"><Logo showTagline /><Link to="/shop" className="inline-flex items-center gap-1 text-sm font-semibold text-sky-900 hover:text-sky-700"><ArrowLeft className="h-4 w-4" /> Shop &amp; Travel</Link></div></header>
    <main className="mx-auto max-w-4xl px-6 py-12"><article className="rounded-xl border border-sky-900/10 bg-white p-6 shadow-sm md:p-10"><div className="flex items-start gap-3"><div className="rounded-lg bg-sky-100 p-2 text-sky-800"><ShieldCheck className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-sky-800">METHO Travel</p><h1 className="mt-1 font-display text-3xl font-black tracking-tight text-emerald-950 md:text-4xl">Travel Booking Terms</h1><p className="mt-2 text-sm text-slate-500">Version 2026-08-19 · Applies to METHO tourism bookings in India.</p></div></div><p className="mt-7 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">Please read these terms before making a travel booking. They are an operational customer policy and should be reviewed by the company&apos;s qualified Indian legal and tax advisers before launch of new destinations, packages, or suppliers.</p><div className="mt-8 space-y-7 text-sm leading-7">{sections.map(([title, body]) => <section key={title}><h2 className="font-display text-xl font-bold text-emerald-950">{title}</h2><p className="mt-2">{body}</p></section>)}</div></article></main>
  </div>;
}