import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";

const sections = [
  ["1. Mandatory acceptance and booking status", "You must read and accept these Travel Booking Terms before payment can be made. Selecting a date, receiving a payment acknowledgement, or receiving an order reference is a booking request only. A booking becomes confirmed only when METHO or the named supplier confirms the itinerary, availability, and booking reference in writing."],
  ["2. METHO's role", "METHO acts only as an intermediary technology platform and administrative facilitator for travel booking and coordination. METHO does not own, operate, inspect, certify, guarantee, or endorse the hotel, transport, guide, activity operator, itinerary, or other independent supplier service, except to the extent expressly confirmed in writing or required by applicable law."],
  ["3. Compliance with Indian law", "Every traveller must comply with all applicable laws of India, state and local authority directions, consumer-protection requirements, tourism and transport rules, entry restrictions, permits, licensing conditions, safety requirements, and lawful instructions of the supplier and authorities. The lead traveller is responsible for ensuring that every person in the booking is legally eligible to travel and has the required documents, permissions, and consent."],
  ["4. Price, inclusions and exclusions", "The displayed amount applies only to the service described in the listing. Transport, meals, entry tickets, permits, taxes, insurance, baggage, personal expenses, supplier surcharges, and other items are excluded unless expressly stated in the written confirmation. A change in traveller count, route, dates, room category, or supplier availability may change the payable amount; any revised amount will require customer approval before collection."],
  ["5. Traveller information and documents", "The lead traveller must provide accurate names, age, contact details, identity documents, permits, visas, medical declarations, and consent for every traveller. METHO does not guarantee admission, boarding, entry, or permit approval where documents, health requirements, age limits, or authority directions are not met."],
  ["6. Cancellation, changes and refunds", "Cancellation or change requests must be made through booking support from the registered mobile number. Refund eligibility, timing, and deductions depend on the confirmed supplier terms, non-refundable components, time before departure, and services already delivered. Statutory, supplier, bank/payment, and disclosed administrative deductions may apply. No refund is due for no-shows, late arrival, incorrect traveller details, or failure to meet required conditions."],
  ["7. Availability, safety and disruption", "Travel is subject to weather, traffic, operational limitations, government or local authority directions, strikes, public-health measures, supplier disruption, and events outside reasonable control. Where possible, METHO will coordinate an alternative, credit, or refund available from the supplier; it cannot promise an outcome beyond the supplier's or customer's legal entitlement. Travellers must follow safety, accommodation, transport, and lawful authority instructions."],
  ["8. Supplier responsibility and complaints", "Hotels, transporters, guides, activity operators, and other third parties remain responsible for services they operate. METHO will reasonably assist with booking coordination and complaint escalation, but does not assume responsibility for an independent supplier's acts, omissions, service quality, or unsafe conduct except where liability cannot lawfully be excluded. Report an on-trip issue promptly with the booking reference and supporting evidence."],
  ["9. Privacy, payment and fraud prevention", "Booking details and limited traveller information are used to arrange the requested service, process payment, provide support, prevent fraud, and meet legal or tax obligations. Information may be shared with the relevant supplier only as needed for the booking. Never share a UPI PIN, card PIN, CVV, or OTP with METHO staff or suppliers. A chargeback or dispute does not by itself cancel a confirmed service."],
  ["10. Consumer rights, governing law and contact", "Nothing in these terms limits rights that cannot be excluded under applicable Indian law. Before payment, review the listing, supplier confirmation, cancellation terms, invoice, and destination-specific requirements. For assistance or a grievance, contact METHO from the registered mobile number and retain the order, payment, and supporting references. These terms are governed by applicable laws of India, subject to mandatory consumer-protection jurisdiction."],
];

export default function TravelBookingTermsPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-700">
    <header className="border-b border-sky-900/10 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4 px-6 py-4"><Logo showTagline /><Link to="/tour-and-travel" className="inline-flex items-center gap-1 text-sm font-semibold text-sky-900 hover:text-sky-700"><ArrowLeft className="h-4 w-4" /> Tour &amp; Travel</Link></div></header>
    <main className="mx-auto max-w-4xl px-6 py-12"><article className="rounded-xl border border-sky-900/10 bg-white p-6 shadow-sm md:p-10"><div className="flex items-start gap-3"><div className="rounded-lg bg-sky-100 p-2 text-sky-800"><ShieldCheck className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-sky-800">METHO Tour &amp; Travels</p><h1 className="mt-1 font-display text-3xl font-black tracking-tight text-emerald-950 md:text-4xl">Travel Booking Terms &amp; Conditions</h1><p className="mt-2 text-sm text-slate-500">Version 2026-08-22 · Applies only to METHO tourism bookings in India.</p></div></div><p className="mt-7 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">Acceptance of these terms is mandatory. The travel booking payment button remains unavailable until the customer accepts them at checkout.</p><div className="mt-8 space-y-7 text-sm leading-7">{sections.map(([title, body]) => <section key={title}><h2 className="font-display text-xl font-bold text-emerald-950">{title}</h2><p className="mt-2">{body}</p></section>)}</div></article></main>
  </div>;
}